require "rugged"
require "gollum_rails/engine"
require "haml"
require "jquery-ui-rails"
require "jquery-rails"
require 'coffee_script'
require 'bootstrap-sass'
require 'bootstrap_form'
require "paperclip"
require 'rails-i18n'
require 'html/pipeline'
